"""add_bio_education_experience_to_doctor

Revision ID: 36b6e8a2d415
Revises: dde091e5c4be
Create Date: 2025-07-03 06:26:09.612863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b6e8a2d415'
down_revision: Union[str, None] = 'dde091e5c4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('education', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('experience', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'experience')
    op.drop_column('doctors', 'education')
    op.drop_column('doctors', 'bio')
    # ### end Alembic commands ###
