"""add_queue_identifier_field

Revision ID: 39ffd2fb0e65
Revises: e9ab91c7218a
Create Date: 2025-07-06 14:39:15.967814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ffd2fb0e65'
down_revision: Union[str, None] = 'e9ab91c7218a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('queue_identifier', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'queue_identifier')
    # ### end Alembic commands ###
