"""add_notification_template_and_update_notification_model

Revision ID: 452b13b5ab78
Revises: 6a87ce0d8d82
Create Date: 2025-06-27 08:14:19.522400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452b13b5ab78'
down_revision: Union[str, None] = '6a87ce0d8d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('SMS', 'EMAIL', 'PUSH', 'SYSTEM', name='notificationtype'), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notification_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_notification_templates_name'))
    )
    op.add_column('notifications', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('notifications', sa.Column('type', sa.Enum('SMS', 'EMAIL', 'PUSH', 'SYSTEM', name='notificationtype'), nullable=True))
    op.add_column('notifications', sa.Column('recipient', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('reference_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_notifications_user_id_users'), 'notifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_notifications_user_id_users'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'recipient')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'user_id')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
