"""added notes and Notes and ConsultationFeedback, and PatientNote table

Revision ID: 6a87ce0d8d82
Revises: dfccd0b618e4
Create Date: 2025-06-27 01:20:18.970500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a87ce0d8d82'
down_revision: Union[str, None] = 'dfccd0b618e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_notes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('doctor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('previous_version_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_patient_notes_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_notes_patient_id_patients')),
    sa.ForeignKeyConstraint(['previous_version_id'], ['patient_notes.id'], name=op.f('fk_patient_notes_previous_version_id_patient_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_notes'))
    )
    op.create_table('consultation_feedback',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('appointment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('doctor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_consultation_feedback_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_consultation_feedback_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_feedback')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_consultation_feedback_appointment_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_feedback')
    op.drop_table('patient_notes')
    # ### end Alembic commands ###
