"""Add emergency contact details

Revision ID: acf30b03052d
Revises: 001
Create Date: 2025-06-16 04:56:57.511368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf30b03052d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'emergency_contact_relationship')
    op.drop_column('patients', 'emergency_contact_name')
    # ### end Alembic commands ###