"""add_shift_times_to_doctor

Revision ID: dde091e5c4be
Revises: 452b13b5ab78
Create Date: 2025-06-27 09:47:26.172077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde091e5c4be'
down_revision: Union[str, None] = '452b13b5ab78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('shift_start', sa.String(length=10), nullable=True))
    op.add_column('doctors', sa.Column('shift_end', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'shift_end')
    op.drop_column('doctors', 'shift_start')
    # ### end Alembic commands ###
