"""add_doctor_id_patient_it_to_queue

Revision ID: e9ab91c7218a
Revises: 36b6e8a2d415
Create Date: 2025-07-03 11:11:48.764858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9ab91c7218a'
down_revision: Union[str, None] = '36b6e8a2d415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('queue', sa.Column('doctor_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_queue_doctor_id_doctors'), 'queue', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('fk_queue_patient_id_patients'), 'queue', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_queue_patient_id_patients'), 'queue', type_='foreignkey')
    op.drop_constraint(op.f('fk_queue_doctor_id_doctors'), 'queue', type_='foreignkey')
    op.drop_column('queue', 'doctor_id')
    op.drop_column('queue', 'patient_id')
    # ### end Alembic commands ###
